# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermap', '0003_news_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.ManyToManyField(related_name='liked_by', to='hypermap.News'),
        ),
    ]
