# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 07:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypermap', '0006_auto_20171201_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 2, 2, 46, 11895)),
        ),
    ]
